### ISSUE TITLE
How use string values instead of numbers

### ISSUE THREAD

**Issue by sant527** [arthanzel/evaluatex#14]
Tried this
```
var evaluatex = require("evaluatex")
exp_function = evaluatex("a*(x+b)")
exp_function({a:10,x:"x",b:"10"})
```
and got
```
/home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:90
                    throw new Error("Symbol " + this.value + " is undefined or not a number");
                    ^

Error: Symbol x is undefined or not a number
    at Node.evaluate (/home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:90:27)
    at /home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:83:44
    at Array.reduce (<anonymous>)
    at Node.evaluate (/home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:82:44)
    at /home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:78:48
    at Array.reduce (<anonymous>)
    at Node.evaluate (/home/simha/maths_testing/node_modules/evaluatex/dist/Node.js:77:44)
    at fn (/home/simha/maths_testing/node_modules/evaluatex/dist/evaluatex.js:33:20)
    at evalmachine.<anonymous>:1:1
    at Script.runInThisContext (vm.js:124:20)
```

I am creating various expressions with some variables. to show for students. 

eg:
```
10*x + 100
```

How can i do this

Also Sometime i only want to substitute

i.e
```
10*(x + 10)
```

**Comment by arthanzel** [comment]
Evaluatex doesn't support symbolic computation. It only evaluates numerically and so every variable must have a numeric value.

I'm working on a better expression engine that will support limited symbolic computations, but that probably won't be coming anytime soon.

If you'd like to demonstrate algebra like this, you can try [Sympy](https://www.sympy.org/en/index.html) or [Mathematica](https://www.wolfram.com/mathematica/).
