### ISSUE TITLE
Error when running build NPM script

### ISSUE THREAD

**Issue by whatl3y** [arthanzel/evaluatex#7]
The following error occurs when running the `build` script. I've tried Node 14.5.0 and 12.x and same error occurs. It looks like index.js falls back to `src/evaluatex` so it might still work fine, but figured we should get this build script working if it needs to remain.

```
evaluatex$ npm run build

> evaluatex@2.1.2 build /Users/lancewhatley/nodejs/evaluatex
> babel -d dist src && webpack dist/minifier.js -o dist/evaluatex.min.js

src/Node.js -> dist/Node.js
src/Token.js -> dist/Token.js
src/evaluatex.js -> dist/evaluatex.js
src/lexer.js -> dist/lexer.js
src/minifier.js -> dist/minifier.js
src/parser.js -> dist/parser.js
src/util/arities.js -> dist/util/arities.js
src/util/isNumber.js -> dist/util/isNumber.js
src/util/localFunctions.js -> dist/util/localFunctions.js
src/util/replaceToken.js -> dist/util/replaceToken.js
/Users/lancewhatley/nodejs/evaluatex/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/lancewhatley/nodejs/evaluatex/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/lancewhatley/nodejs/evaluatex/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/lancewhatley/nodejs/evaluatex/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! evaluatex@2.1.2 build: `babel -d dist src && webpack dist/minifier.js -o dist/evaluatex.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the evaluatex@2.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancewhatley/.npm/_logs/2020-07-12T11_52_26_156Z-debug.log
```

**Comment by arthanzel** [comment]
I can't reproduce this with Node 12.10.0. `yarn build` and `npm run build` succeed just fine off a fresh clone (though the webpack config needs to be updated to rid a warning).

From the error, it looks like there's something funky within Webpack itself. Have you tried `rm -rf node_modules`, or building off a fresh clone? Is there a globally-installed version of webpack that is interfering? Does `yarn build` produce the same error?

If none of that gets you anywhere, can you paste the latest log at `/Users/lancewhatley/.npm/_logs/2020-07-12Txxxxxxxxx-debug.log`?
